name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    deply_job:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Establish a Connection to Server and Update Website
              uses: appleboy/ssh-action@master
              with:
                  host: 130.185.76.173
                  username: root
                  key: ${{secrets.SSH_KEY}}
                  port: 22
                  script: |
                      cd /repos/playground-flip
                      git fetch
                      git checkout master
                      git reset --hard HEAD
                      git pull origin master
                      npm i
                      ng build --base-href=/flip/
                      rm -rf /var/playground/bijanprogrammer.com/html/flip
                      cp -a dist/flip/. /var/playground/bijanprogrammer.com/html/flip
