name: Deploy
on:
    push:
        branches: [main]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            host: playground.bijanprogrammer.com
            base-href: /flip/
            project-name: flip
